export interface WPImage {
    ID: number,
    id: number,
    title: string,
    filename: string,
    url: string,
    link: string,
    alt: string,
    author: string,
    description: string,
    caption: string,
    name: string,
    status: string,
    uploaded_to: number,
    date: string,
    modified: string,
    menu_order: number,
    mime_type: string,
    type: string,
    subtype: string,
    icon: string,
    width: number,
    height: number,
    sizes: {
        thumbnail: string,
        ['thumbnail-width']: number,
        ['thumbnail-height']: number,
        medium: string,
        ['medium-width']: number,
        ['medium-height']: number,
        large: string,
        ['large-width']: number,
        ['large-height']: number,
    }
}
